apiVersion: v1
kind: Service
metadata:
  name: svc-alertmanager-forwarder
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: alertmanager-forwarder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
