---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertmanager
  name: svc-alertmanager
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: alertmanager
    port: 9093
  selector:
    app: alertmanager