kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:

    route:
      group_by: ['alertname']

      group_wait: 30s
      group_interval: 10m
      repeat_interval: 1h

      receiver: webhook

      routes:
        - match:
            severity: warning
          continue: true
          receiver: webhook

    receivers:
      - name: webhook
        webhook_configs: #
          - url: 'http://svc-alertmanager-forwarder.monitoring.svc.cluster.local'